name: ci-analyze
run-name: CI Analyze
on:
  pull_request:
    types: [opened, reopened]
  push:
    branches: 
    - integration
    - uvc-*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running" >> "$GITHUB_OUTPUT"
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '18'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: client/pubspec.yaml
          cache: true
      - name: Install dependencies
        run: flutter pub get
        working-directory: client
      - name: Analyze
        shell: pwsh
        run: ../.ci/flutterAnalyze.ps1
        working-directory: client
