name: ci-debug
run-name: CI Debug
on:
  pull_request:
    branches:
    - integration
  push:
    branches: 
    - integration
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '18'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: client/pubspec.yaml
          cache: true
      - name: Install dependencies
        run: flutter pub get
        working-directory: client
      - name: Create secrets.env
        run: >
         touch secrets.env && 
         echo "AUTH0_DOMAIN=domain" >> secrets.env && 
         echo "AUTH0_CLIENT_ID=clientId" >> secrets.env && 
         echo "AUTH0_AUDIENCE=audience" >> secrets.env 
        working-directory: client
      - name: Generate code
        run: dart run build_runner build --delete-conflicting-outputs
        working-directory: client
      - name: Static analysis
        run: chmod +x ../.ci/flutterAnalyze.sh && ../.ci/flutterAnalyze.sh
        working-directory: client
      - name: Build
        run: flutter build apk --debug
        working-directory: client
