name: CI
run-name: ${{ github.actor }} is learning gitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '18'
      # - name: Setup Gradle
      #   uses: gradle/actions/setup-gradle@v3
      - name: Set up android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 11076708
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: client/pubspec.yaml
      - name: Run flutter doctor
        run: flutter doctor -v 