name: CI
run-name: ${{ github.actor }} is learning gitHub Actions
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '18'
      - name: Set up android sdk 31
        uses: android/setup-android@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: client/pubspec.yaml
      - name: Install dependencies
        run: flutter pub get
        working-directory: client
      - name: Build debug
        run: flutter build apk --debug
        working-directory: client