name: Create and publish an apk to the assets

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '18'
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: client/pubspec.yaml
          cache: true
      - name: Install dependencies
        run: flutter pub get
        working-directory: client
      - name: Decode and save keystore
        env:
          KEYSTORE_JKS_B64: ${{ secrets.KEYSTORE_JKS_B64 }}
        run: |
          echo -n "$KEYSTORE_JKS_B64" | base64 --decode > upload-keystore.jks
        working-directory: client/android
      - name: Create key.properties file
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        run: >
         touch key.properties && 
         echo "storePassword=$KEYSTORE_PASSWORD" >> key.properties && 
         echo "keyAlias=upload" >> key.properties && 
         echo "keyPassword=$KEYSTORE_PASSWORD" && >> key.properties
         echo "storeFile=upload-keystore.jks" >> key.properties
        working-directory: client/android
      - name: Create secrets.env
        env:
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
        run: >
         touch secrets.env && 
         echo "AUTH0_DOMAIN=$AUTH0_DOMAIN" >> secrets.env && 
         echo "AUTH0_CLIENT_ID=$AUTH0_CLIENT_ID" >> secrets.env && 
         echo "AUTH0_AUDIENCE=$AUTH0_AUDIENCE" >> secrets.env &&
         echo "UP_VIBE_SERVER_IP=$UP_VIBE_SERVER_IP" >> secrets.env
        working-directory: client
      - name: Generate code
        run: dart run build_runner build --delete-conflicting-outputs
        working-directory: client
      - name: Static analysis
        run: chmod +x ../.ci/flutterAnalyze.sh && ../.ci/flutterAnalyze.sh
        working-directory: client
      - name: Build
        run: flutter build apk
        working-directory: client
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "client/build/app/outputs/flutter-apk/app-release.apk"
